### ISSUE TITLE
Requirement for composer <= 1.8.0

### ISSUE THREAD

**Issue by gwharton** [magento/composer-root-update-plugin#11]
Can we review the requirement for composer <=1.8.0. My stores are locked at 1.9.0 and so cannot use this plugin any more.

**Comment by pdohogne-magento** [comment]
Yes, this will be reviewed before 1.0 release.  Thank you for the reminder.

**Comment by JeroenBoersma** [comment]
Can someone tag `0.1.1` so we can use it for the Magento 2.3.5 which has `composer/composer: ^1.9`
