### ISSUE TITLE
Can't install Version 1.0

### ISSUE THREAD

**Issue by EFvS** [magento/composer-root-update-plugin#13]
I've been trying to install magento/composer-root-update-plugin via composer, but the version 1.0 isn't on repo.magento.com.
Manual installation won't work, because we need the composer.json from the src folder.
Can you please release 1.0 to the marketplace?

**Comment by pdohogne-magento** [comment]
Hello @EFvS !  Thank you for your comment.  The issue should be resolved, can you please try again now and report back?

**Comment by EFvS** [comment]
@pdohogne-magento Thank you for your fast response. The installation works now.
