### ISSUE TITLE
Can not upgrade to 2.3.6

### ISSUE THREAD

**Issue by larsroettig** [magento/composer-root-update-plugin#17]
```
composer require magento/product-enterprise-edition 2.3.6 --base-magento-edition Commerce --base-magento-version 2.3.5-p2
```

Error:
```
  Problem 1
    - Can only install one of: magento/page-builder-commerce[1.3.3, 1.3.2].
    - Can only install one of: magento/page-builder-commerce[1.3.2, 1.3.3].
    - Can only install one of: magento/page-builder-commerce[1.3.3, 1.3.2].
    - magento/product-enterprise-edition 2.3.6 requires magento/page-builder-commerce 1.3.3 -> satisfiable by magento/page-builder-commerce[1.3.3].
    - Installation request for magento/product-enterprise-edition 2.3.6 -> satisfiable by magento/product-enterprise-edition[2.3.6].
    - Installation request for magento/page-builder-commerce (locked at 1.3.2, required as ~1.3.2) -> satisfiable by magento/page-builder-commerce[1.3.2].
```

**Comment by pdohogne-magento** [comment]
@larsroettig Have you previously added `magento/page-builder-commerce` to the composer.json file?  If not (which is generally expected), try running that `composer require` command with the `--no-update` option as documented then running `composer update` afterwards.

As a side note, you shouldn't need those `--base-magento` options if you are upgrading from 2.3.5-p2; those are only used if your composer.json file is outdated from a previous version than is currently installed (they tell the plugin to use a different Magento version as the base than the one that's currently in the lock file).

**Comment by larsroettig** [comment]
with `--no-update` it works fine
