### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jimmybsilva** [magento/composer-root-update-plugin#19]
`composer require magento/composer-root-update-plugin ~1.1 --no-update`

> ./composer.json has been updated

` composer update`

> Problem 1
    - The requested package magento/composer-root-update-plugin ~1.1 exists as magento/composer-root-update-plugin[1.0.0, 0.1.1, 0.1.0] but these are rejected by your constraint.

Why do I get the following error?

**Comment by mhodge13** [comment]
+1

**Comment by bsdonaldson** [comment]
@jimmybsilva I think if you have composer 1.x installed you can only install version 1.0.0 whereas 1.1.0 adds support for Composer 2.0. As a workaround you can install version 1.0.0 of this extension or upgrade to composer 2.

This works for me, so hopefully helps you out too.

**Comment by pdohogne-magento** [comment]
`magento/composer-root-update-plugin` version 1.1.0 has not been fully released on repo.magento.com when this ticket was opened and may not have been accessible.  Please try again now.

@BrianSDonaldson Of note, version 1.1.0 is compatible with both Composer 1.x and Composer 2.0, so you should not need to upgrade to Composer 2 to use the new version of the plugin.

**Comment by mhodge13** [comment]
Version 1.1.0 is working successfully.  This issue is now resolved for me.
