### ISSUE TITLE
Composer requirement: Not available to set up on Composer 1.10.20 or 2.0.9

### ISSUE THREAD

**Issue by vmalyk** [magento/composer-root-update-plugin#20]
According requirements for Composer version:
`"composer/composer": "<=1.10.19 || >=2.0.0 <=2.0.8",`

It's strict requirements and require to create new package version for each patch Composer upgrade with important fixes.

I suggest to change requirement to less strict and release new version in  minor version change, like:
`"composer/composer": "< 1.11 || ~2.0.0",`  

Please review suggestion or add 1.10.20 and 2.0.9 to supported version list.
Thank you!

**Comment by pdohogne-magento** [comment]
Unfortunately this plugin depends on private code in the Composer framework, which means we cannot guarantee it will be compatible with new versions of Composer (even patch releases) until it has been tested on our side, and thus we cannot loosen the composer constraint.

**Comment by PorraphitChuasuk** [comment]
I never notice this restriction until update composer from 2.0.9 to 2.0.10, I think it start incompatible with internal composer.

On Magento root project, I remove `vendor/*` and `var/vendor/*`
```
# composer -V
Composer version 2.0.10 2021-02-23 16:11:37
# composer install --ignore-platform-reqs --no-interaction --no-dev
```

And got this error.
```
Fatal error: Uncaught TypeError: Argument 4 passed to Composer\Repository\Vcs\VcsDriver::__construct() must be an instance of Composer\Util\ProcessExecutor or null, instance of Composer\Util\HttpDownloader given, called in phar:///usr/bin/composer/src/Composer/Repository/VcsRepository.php on line 121 and defined in /app/vendor/composer/composer/src/Composer/Repository/Vcs/VcsDriver.php:60
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Repository/VcsRepository.php(121): Composer\Repository\Vcs\VcsDriver->__construct(Array, Object(Composer\IO\ConsoleIO), Object(Composer\Config), Object(Composer\Util\HttpDownloader), Object(Composer\Util\ProcessExecutor))
#1 phar:///usr/bin/composer/src/Composer/Repository/VcsRepository.php(160): Composer\Repository\VcsRepository->getDriver()
#2 phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php(266): Composer\Repository\VcsRepository->initialize()
#3 phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php(55): Composer\Repository\ArrayRepository->getPac in /app/vendor/composer/composer/src/Composer/Repository/Vcs/VcsDriver.php on line 60

```

**Comment by pdohogne-magento** [comment]
Composer compatibility up to versions 1.10.20 and 2.0.11 has been added in version 1.1.1.
