### ISSUE TITLE
Update Composer version constraint to allow for 1.10.21

### ISSUE THREAD

**Issue by Serializator** [magento/composer-root-update-plugin#23]
In Composer 1.10.21 a patch was introduced for an issue related to the new OAuth token format that GitHub started using.
https://github.com/composer/composer/commit/dc83ba93f3d8a35629f9a387632e8cd373a144d0

**Comment by manuel-boesch-fricke** [comment]
Magento CLI is broken when using a dependency from github. 
Every command results in 
`Your github oauth token for github.com contains invalid characters: "ghp_secretgithubtoken"#0 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(325): Composer\IO\BaseIO->loadConfiguration(Object(Composer\Config))
#1 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#2 /var/www/html/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/var/www/html/c...')
#3 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(368): Magento\Framework\Composer\ComposerFactory->create()
#4 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(381): Magento\Framework\Composer\ComposerInformation->getComposer()
#5 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(244): Magento\Framework\Composer\ComposerInformation->getLocker()
#6 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(120): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#7 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(80): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#8 /var/www/html/vendor/magento/framework/Console/Cli.php(98): Magento\Framework\App\ProductMetadata->getVersion()
#9 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#10 {main}`

**Comment by Serializator** [comment]
I created a pull request (https://github.com/magento/composer-root-update-plugin/pull/24) for this issue.
