### ISSUE TITLE
magento setup:compile error 

### ISSUE THREAD

**Issue by raxithrai** [magento/composer-root-update-plugin#29]
Hello All,

I got a new issue during the magento compile:

i used to run compile 
![Screenshot (374)](https://user-images.githubusercontent.com/53504686/134767002-2135edb4-3a03-4850-ba87-2f0801ed9cbf.png)
 **php -dmemory_limit=4G bin/magento setup:di:compile** in command prompt

C:\xampp\htdocs\magento>**php -dmemory_limit=4G bin/magento setup:di:compile**
Compilation was started.
**Plugin list generation... 8/9 [========================>---]  88% 4 mins 372.0 MiB**
In ErrorHandler.php line 61:

  **Warning: file_put_contents**(C:/xampp/htdocs/magento/generated/metadata/primary|global|plugin-list.php): **failed to op
  en stream: No such file or directory** in C:\xampp\htdocs\magento\vendor\magento\framework\Interception\**PluginListGen
  erator.php on line 414**

setup:di:compile

**Comment by pdohogne-magento** [comment]
Hey @raxithrai, sorry for the delay in responding to this issue.  Unfortunately the problem you've reported here does not have anything to do with this plugin (which is a composer plugin, not a Magento plugin -- confusing, believe me I know).  If you are still experiencing this issue, please report it on https://github.com/magento/magento2 or open a support ticket.
