### ISSUE TITLE
Code and tag 2.0.2 missing

### ISSUE THREAD

**Issue by Vinai** [magento/composer-root-update-plugin#35]
On a Magento Open Source 2.4.4 install, `magento/composer-dependency-version-audit-plugin` version 2.0.2 is installed.

However, this repository hasn't been updated. The tag is missing, and, what's more, the code isn't there either.

**Comment by fooman** [comment]
@Vinai this issue might be in the wrong repo - the tag is still missing there as well though
https://github.com/magento/composer-dependency-version-audit-plugin/tags

**Comment by sidolov** [comment]
Hi @Vinai! We will update the repo shortly!

**Comment by Vinai** [comment]
Thanks @sidolov 

@fooman the dependency-version-audit-plugin didn't get an update from what I can see. Still version 0.1.1 installing on 2.4.4

However, there is also an issue with 0.1.2 having the same tag as 0.1.1 there, but 🤷  it's easier to work around that issue.

**Comment by Vinai** [comment]
Thanks for the tags! 🎉
